--[[  __         __          __________
     /  \       /  \        / ________/     
	/ /\ \     / /\ \      / /_______                             
   / /  \ \   / /  \ \    /_______  /  
  /	/    \ \_/ /    \ \  ________/ /    
 / /      \___/      \ \/_________/         
 🍊 MANDALİNA STUDIO © 2025 By ProfDrOsman 🍊
           [Overhead GUI] 
    github.com/ProfDrOsman
    github.com/MandalinaStudio
    
    Part/BillboardGui/Rank/Script
]]--
local head = script.Parent.Parent.Parent
local chr = head.Parent
local plr = game.Players:GetPlayerFromCharacter(chr)
local text = script.Parent

text.TextColor3 = Color3.fromRGB(255, 255, 255)
text.Text = "Player"
